### PR TITLE
Don't submit form if non-Element inputs fail validation.

### LINKED ISSUE #35: Enter key within card fields doesn't validate other fields.
When you hit Enter within one of the card fields, the validation rules on all the non-card fields is ignored and the form submits. However, validation is triggered properly if the Pay button is clicked instead. Tried this with the first 2 examples.

### PR DESCRIPTION
**Pull request by jenan-stripe**
r? @jez-stripe 

Fixes #35.

Don't submit form if non-Element inputs fail validation.

In these examples, we use the basic HTML5 form validation APIs (e.g. the
`required` attribute) for validation on non-Elements inputs.

If an Element is focused and a user submit event is triggered (e.g.
through the enter key), the DOM does not automatically trigger form
validation on the outer plain inputs. This previously allowed submission
of the form with empty `required` fields.

This change catches those cases by manually triggering HTML5 form
validation on submit.

### CODE REVIEW

File: js/index.js [hunk 1]
```diff
@@ -66,6 +77,22 @@ function registerElements(elements, exampleName) {
   form.addEventListener('submit', function(e) {
     e.preventDefault();
 
+    // Trigger HTML5 validation UI on the form if any of the inputs fail
+    // validation.
+    var plainInputsValid = true;
+    Array.prototype.forEach.call(form.querySelectorAll('input'), function(
```
Comment (jez) [inline js/index.js]: I'm assuming the `Array.prototype.forEach.call` is because `querySelector` doesn't return an Array?

File: js/index.js [hunk 2]
```diff
@@ -66,6 +77,22 @@ function registerElements(elements, exampleName) {
...
+      input
+    ) {
+      if (input.checkValidity && !input.checkValidity()) {
+        plainInputsValid = false;
```
Comment (jez) [inline js/index.js]: I think I personally would have used `Array.prototype.reduce` to avoid the mutation, but this is 👍 too.

File: js/index.js (hunk 1 above)
Comment (jenan-stripe) [reply js/index.js]: Yup! Not all browsers implement `NodeLIst.forEach`.
